install.packages("devtools")
install.packages("pacman")
install.packages("tidyverse")
install.packages("haven")

install.packages('car')
install.packages('AER')
install.packages('plm')
install.packages("stargazer")

install.packages("knitr")
install.packages("rmarkdown")
install.packages('bookdown')
install.packages('tinytex')
tinytex::install_tinytex()

install.packages(c("ggpubr", "here", "rstatix", "summarytools"))

# install.packages('broom')
# install.packages('clubSandwich')
# install.packages('dlookr')
# install.packages('ExPanDaR')
# install.packages('fixest')
# install.packages('funModeling')
# install.packages('gplots')
# install.packages('Hmisc')
# install.packages('janitor')
# install.packages('kableExtra')
# install.packages('lfe')
# install.packages('lmtest')
# install.packages('MASS')
# install.packages('naniar')
# install.packages('PoEdata')
# install.packages('robustbase')
# install.packages('sandwich')
# install.packages('SmartEDA')
# install.packages('tseries')
# install.packages('visdat')
